package com.wupipi.tankwar;

public enum ImageType {
  WALL, GRID, GRASS, ICE, WATER,
  HOME, HOME_DESTROYED, HOME_PLACEHOLDER,
  FOOD_LIFE, FOOD_FREEZE, FOOD_HOME_DEFENCE, FOOD_BOMB, FOOD_STAR, FOOD_GOD
}
