package com.wupipi.battlecity;

public enum ImageType {
    WALL, GRID, GRASS, ICE, WATER,
    HOME, HOME_DESTROYED, HOME_PLACEHOLDER,
    FOOD_LIFE, FOOD_FREEZE, FOOD_HOME, FOOD_BOMB, FOOD_PROMOTION, FOOD_GOD,
    TANK_PLAYER, TANK_NPC_NORMAL, TANK_NPC_RACER, TANK_NPC_ARMOR, BULLET
}
